### ISSUE TITLE
Cannot insert a bookmark if the target is non-html

### ISSUE THREAD

**Issue by sainigma** [sainigma/ohtu-miniprojekti#2]
If a url that points to a non-html target (pdf, image etc.) is inserted, the program crashes. The fault is probably in the response parsing.

**Comment by Veikkosuhonen** [comment]
Fixed by [eb2123b9cb0c10ecd5b8edee9d994fcf9f67f462](https://github.com/sainigma/ohtu-miniprojekti/commit/eb2123b9cb0c10ecd5b8edee9d994fcf9f67f462)
